variables:
  COV_MODULE: quantify_core
  WEBSITE_DEPLOY_PATH: "docs/quantify-core"

include:
  - project: "quantify-os/ci"
    ref: add_sphinx_error_log_to_artifacts
    file: "/python-quantify.yml"

